services:
  - postgres:latest

stages:
- test
- lint
- docker

variables:
  POSTGRES_DB: $DB
  POSTGRES_USER: $DB_USER
  POSTGRES_PASSWORD: $DB_PW
  REGISTRY: ghcr.io

cache:
  paths:
    - vendor/ruby

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

rubocop:
  stage: lint
  before_script:
    - ruby -v
    - bundle config set --local deployment true
    - bundle install -j $(nproc)
  script:
    - bundler exec rubocop
  image: ruby:latest

rspec:
  stage: test 
  before_script:
    - ruby -v
    - bundle config set --local deployment true
    - bundle install -j $(nproc)
    - mkdir lib/backup lib/log
  script:
    - bundle exec rspec spec -r rspec_junit_formatter --format RspecJunitFormatter -o coverage/rspec.xml
  artifacts:
    when: always
    paths:
      - coverage/
    reports:
      junit: coverage/rspec.xml
  image: ruby:latest

docker_build:
  stage: docker
  services:
    - docker:dind
  before_script:
    - docker login $REGISTRY -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build --pull -t "postgresql_brm" .
    # latest tag
    - docker tag "postgresql_brm" "$REGISTRY/$PROJECT_NAMESPACE/postgresql_brm:latest"
    - docker push "$REGISTRY/$PROJECT_NAMESPACE/postgresql_brm:latest"
    # version tag
    - docker tag "postgresql_brm" "$REGISTRY/$PROJECT_NAMESPACE/postgresql_brm:$CI_COMMIT_TAG"
    - docker push "$REGISTRY/$PROJECT_NAMESPACE/postgresql_brm:$CI_COMMIT_TAG"
  image: docker:cli
  only:
    - tags
