AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Max: 85

Metrics/MethodLength:
  Max: 30

Layout/LineLength:
  Max: 350
  
Style/GuardClause:
  Enabled: false
